### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by PacificBlackDuck** [mcumbers/twitchcord#3]
![image](https://cloud.githubusercontent.com/assets/20697185/26052220/1add7cac-39a8-11e7-9c75-2f192ffe08cc.png)
not sure what i did wrong

![image](https://cloud.githubusercontent.com/assets/20697185/26052400/c0e89afa-39a8-11e7-9d67-5ed74f776901.png)

**Comment by jankcat** [comment]
@decoratedbug what version of node are you running?
do an `npm version` and post the output

**Comment by mcumbers** [comment]
Looks like the issue is with (_very_) old versions of Node. Adding requirement to `package.json` for versions above `4.0.0`.

Update your node to be `4.0.0` or above and it should work.
![screenshot from 2017-05-15 13-41-36](https://cloud.githubusercontent.com/assets/16696023/26078511/a3d3bf8c-3974-11e7-8690-d3997dc1e32f.png)

**Comment by jankcat** [comment]
Ref: http://node.green/#ES2015-functions-arrow-functions
